apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: app-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: resolt123/terbangin:BE-V2
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: "100m"
              memory: "200Mi"
            limits:
              cpu: "200m"
              memory: "400Mi"
          env:
            - name: MYSQL_HOST
              value: "mysql"
            - name: CLIENT_URL
              value: "http://localhost:30007"

---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: app-namespace
spec:
  type: NodePort
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30001
