apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: app-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: resolt123/terbangin:DB-V1
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mysql-data
          mountPath: /var/lib/mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "sukses"
        - name: MYSQL_DATABASE
          value: "terbangin"
      volumes:
      - name: mysql-data
        persistentVolumeClaim:
          claimName: mysql-pvc  # Hubungkan PVC ke volume ini
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: app-namespace
spec:
  selector:
    app: mysql
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306
